import { Consult } from './mockData';

export const sampleConsults: Consult[] = [
  {
    id: 'consult-001',
    patientId: 'patient-001',
    physicianId: 'phys-1',
    stateAtService: 'CA',
    coverageAttested: true,
    redFlag: false,
    topic: 'Red or irritated eye',
    questionBody: 'My left eye has been red and itchy for the past 3 days. It feels gritty and produces some discharge in the morning. No pain or vision changes.',
    status: 'pending',
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    patientInitials: 'JD',
    patientAge: 42,
    pain: 1,
    blur: 0,
    lightSensitivity: 2,
    redness: 7,
    medications: 'lisinopril, metformin',
    allergies: 'Penicillin',
  },
  {
    id: 'consult-002',
    patientId: 'patient-002',
    physicianId: 'phys-1',
    stateAtService: 'NY',
    coverageAttested: true,
    redFlag: false,
    topic: 'Stye or eyelid bump',
    questionBody: 'I have a small painful bump on my upper eyelid that appeared yesterday. It\'s tender to touch and slightly swollen.',
    status: 'pending',
    submittedAt: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    patientInitials: 'SM',
    patientAge: 28,
    pain: 4,
    blur: 0,
    lightSensitivity: 0,
    redness: 3,
    medications: 'None',
    allergies: 'None',
  },
  {
    id: 'consult-001',
    patientId: 'patient-001',
    physicianId: 'phys-1',
    stateAtService: 'CA',
    coverageAttested: true,
    redFlag: false,
    topic: 'Red or irritated eye',
    questionBody: 'My left eye has been red and itchy for the past 3 days. It feels gritty and produces some discharge in the morning. No pain or vision changes.',
    status: 'draft',
    submittedAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    patientInitials: 'JD',
    patientAge: 42,
    pain: 1,
    blur: 0,
    lightSensitivity: 2,
    redness: 7,
    medications: 'lisinopril, metformin',
    allergies: 'Penicillin',
  },
  {
    id: 'consult-003',
    patientId: 'patient-003',
    physicianId: 'phys-1',
    stateAtService: 'TX',
    coverageAttested: true,
    redFlag: false,
    topic: 'Dry eye symptoms',
    questionBody: 'My eyes have been feeling very dry and burning, especially when I work on the computer. I\'ve tried artificial tears but they only help temporarily.',
    status: 'accepted',
    submittedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    acceptedAt: new Date(Date.now() - 20 * 60 * 60 * 1000).toISOString(),
    patientInitials: 'RK',
    patientAge: 55,
    pain: 2,
    blur: 1,
    lightSensitivity: 3,
    redness: 4,
    medications: 'atorvastatin, aspirin',
    allergies: 'None',
  },
];
